### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by DelviousCrafts** [hypherionmc/CraterLib#5]
The latest update causes an inability to connect to a server with an error that states connection reset with no further information. The log indicates an error with advancements. Reverting to the previous version fixes this issue. 

[Latest Server Log](https://gist.github.com/DelviousCrafts/91104b890b6030d9c273b9f9cac951bd)

Versions: 
- Minecraft: 1.20.1
- Forge: 47.2.19
- CraterLib: 1.1.0

**Comment by hypherionmc** [comment]
Hi. Thanks for reporting.

Seems there is a random edge case where the advancement itself is not available. It wasn't a problem before because Simple Discord Link handled the error, so it would just ignore it.

I am currently at work, but a fix for this will be pushed out later today

This affects both fabric and forge, and if I'm not mistaken, only 1.18.2-1.20.1

**Comment by 2el222** [comment]
It does affect Fabric
[latest.log](https://github.com/firstdarkdev/CraterLib/files/13820797/latest.log)

**Comment by hypherionmc** [comment]
> This affects both fabric and forge

Yup. It uses the same code, so that's why I said it will affect both. It just doesn't affect 1.20.2 and up

**Comment by hypherionmc** [comment]
Patch has been released for all affected versions. 1.1.1. 

It's live on Modrinth already and should be live on curseforge soon, if their scanners don't break down again. Thanks for the reports
